
.phony: all

all:
	LD_LIBRARY_PATH=../../src/.libs python library.py
	LD_LIBRARY_PATH=../../src/.libs python environment.py
	LD_LIBRARY_PATH=../../src/.libs python database.py
	LD_LIBRARY_PATH=../../src/.libs python cursor.py
	LD_LIBRARY_PATH=../../src/.libs python transaction.py
	LD_LIBRARY_PATH=../../src/.libs python uqi.py
