#
# Copyright (C) Christoph Rupp, 2005, 2006 (chris@crupp.de)
# see file LICENSE for license and copyright information
#
# Scons file for unit tests
#
#

files=[
        "db.c",
        "main.c",
        "getopts.c"
    ]

Import('env')

libraries = ['hamsterdb', 'db', 'c']
ldflags = []
if env['profile']:
    ldflags.append(['-pg'])
libpaths  = ['../build']

# we have to remove -ansi from CFLAGS because berkeleyDb doesn't like it
l=['-DHAM_DEBUG']
for f in env['CCFLAGS']:
    if f!='-ansi':
        l.append(f)
env['CCFLAGS']=l

# set up the environment
env.Program('test', files, LIBS = libraries, LIBPATH = libpaths, LDFLAGS = ldflags)
