/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_hamsterdb_Cursor */

#ifndef _Included_de_crupp_hamsterdb_Cursor
#define _Included_de_crupp_hamsterdb_Cursor
#ifdef __cplusplus
extern "C" {
#endif
#undef de_crupp_hamsterdb_Cursor_HAM_CURSOR_FIRST
#define de_crupp_hamsterdb_Cursor_HAM_CURSOR_FIRST 1L
#undef de_crupp_hamsterdb_Cursor_HAM_CURSOR_LAST
#define de_crupp_hamsterdb_Cursor_HAM_CURSOR_LAST 1L
#undef de_crupp_hamsterdb_Cursor_HAM_CURSOR_NEXT
#define de_crupp_hamsterdb_Cursor_HAM_CURSOR_NEXT 1L
#undef de_crupp_hamsterdb_Cursor_HAM_CURSOR_PREVIOUS
#define de_crupp_hamsterdb_Cursor_HAM_CURSOR_PREVIOUS 1L
/*
 * Class:     de_crupp_hamsterdb_Cursor
 * Method:    ham_cursor_create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_hamsterdb_Cursor_ham_1cursor_1create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_crupp_hamsterdb_Cursor
 * Method:    ham_cursor_clone
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_hamsterdb_Cursor_ham_1cursor_1clone
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_crupp_hamsterdb_Cursor
 * Method:    ham_cursor_move
 * Signature: (JLde/crupp/hamsterdb/Key;Lde/crupp/hamsterdb/Record;I)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Cursor_ham_1cursor_1move
  (JNIEnv *, jobject, jlong, jobject, jobject, jint);

/*
 * Class:     de_crupp_hamsterdb_Cursor
 * Method:    ham_cursor_overwrite
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Cursor_ham_1cursor_1overwrite
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     de_crupp_hamsterdb_Cursor
 * Method:    ham_cursor_find
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Cursor_ham_1cursor_1find
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     de_crupp_hamsterdb_Cursor
 * Method:    ham_cursor_insert
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Cursor_ham_1cursor_1insert
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     de_crupp_hamsterdb_Cursor
 * Method:    ham_cursor_erase
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Cursor_ham_1cursor_1erase
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_hamsterdb_Cursor
 * Method:    ham_cursor_get_duplicate_count
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Cursor_ham_1cursor_1get_1duplicate_1count
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_hamsterdb_Cursor
 * Method:    ham_cursor_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Cursor_ham_1cursor_1close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
