/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_hamsterdb_Database */

#ifndef _Included_de_crupp_hamsterdb_Database
#define _Included_de_crupp_hamsterdb_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_get_version
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Database_ham_1get_1version
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_get_license
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_crupp_hamsterdb_Database_ham_1get_1license
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_set_errhandler
 * Signature: (Lde/crupp/hamsterdb/ErrorHandler;)V
 */
JNIEXPORT void JNICALL Java_de_crupp_hamsterdb_Database_ham_1set_1errhandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_hamsterdb_Database_ham_1new
  (JNIEnv *, jobject);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_crupp_hamsterdb_Database_ham_1delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_create_ex
 * Signature: (JLjava/lang/String;II[Lde/crupp/hamsterdb/Parameters;)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Database_ham_1create_1ex
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jobjectArray);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_open_ex
 * Signature: (JLjava/lang/String;I[Lde/crupp/hamsterdb/Parameters;)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Database_ham_1open_1ex
  (JNIEnv *, jobject, jlong, jstring, jint, jobjectArray);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_get_error
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Database_ham_1get_1error
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_set_compare_func
 * Signature: (JLde/crupp/hamsterdb/Comparable;)V
 */
JNIEXPORT void JNICALL Java_de_crupp_hamsterdb_Database_ham_1set_1compare_1func
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_set_prefix_compare_func
 * Signature: (JLde/crupp/hamsterdb/PrefixComparable;)V
 */
JNIEXPORT void JNICALL Java_de_crupp_hamsterdb_Database_ham_1set_1prefix_1compare_1func
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_enable_compression
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Database_ham_1enable_1compression
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_find
 * Signature: (J[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_crupp_hamsterdb_Database_ham_1find
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_flush
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Database_ham_1flush
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_insert
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Database_ham_1insert
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_erase
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Database_ham_1erase
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     de_crupp_hamsterdb_Database
 * Method:    ham_close
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_hamsterdb_Database_ham_1close
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
