/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_hamsterdb_Error */

#ifndef _Included_de_crupp_hamsterdb_Error
#define _Included_de_crupp_hamsterdb_Error
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_crupp_hamsterdb_Error
 * Method:    ham_strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_crupp_hamsterdb_Error_ham_1strerror
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
