/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_upscaledb_Transaction */

#ifndef _Included_de_crupp_upscaledb_Transaction
#define _Included_de_crupp_upscaledb_Transaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_crupp_upscaledb_Transaction
 * Method:    ups_txn_commit
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Transaction_ups_1txn_1commit
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_upscaledb_Transaction
 * Method:    ups_txn_abort
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Transaction_ups_1txn_1abort
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
