/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_hamsterdb_Version */

#ifndef _Included_de_crupp_hamsterdb_Version
#define _Included_de_crupp_hamsterdb_Version
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
