/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_upscaledb_CompareCallback */

#ifndef _Included_de_crupp_upscaledb_CompareCallback
#define _Included_de_crupp_upscaledb_CompareCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
