/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_upscaledb_DatabaseException */

#ifndef _Included_de_crupp_upscaledb_DatabaseException
#define _Included_de_crupp_upscaledb_DatabaseException
#ifdef __cplusplus
extern "C" {
#endif
#undef de_crupp_upscaledb_DatabaseException_serialVersionUID
#define de_crupp_upscaledb_DatabaseException_serialVersionUID -3042686055658047285LL
#undef de_crupp_upscaledb_DatabaseException_serialVersionUID
#define de_crupp_upscaledb_DatabaseException_serialVersionUID -3387516993124229948LL
/*
 * Class:     de_crupp_upscaledb_DatabaseException
 * Method:    ups_strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_crupp_upscaledb_DatabaseException_ups_1strerror
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
