/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_hamsterdb_License */

#ifndef _Included_de_crupp_hamsterdb_License
#define _Included_de_crupp_hamsterdb_License
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
