/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_upscaledb_Database */

#ifndef _Included_de_crupp_upscaledb_Database
#define _Included_de_crupp_upscaledb_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_get_version
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Database_ups_1get_1version
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_set_errhandler
 * Signature: (Lde/crupp/upscaledb/ErrorHandler;)V
 */
JNIEXPORT void JNICALL Java_de_crupp_upscaledb_Database_ups_1set_1errhandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_register_compare
 * Signature: (Ljava/lang/String;Lde/crupp/upscaledb/CompareCallback;)V
 */
JNIEXPORT void JNICALL Java_de_crupp_upscaledb_Database_ups_1register_1compare
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_db_set_compare_func
 * Signature: (JLde/crupp/upscaledb/CompareCallback;)V
 */
JNIEXPORT void JNICALL Java_de_crupp_upscaledb_Database_ups_1db_1set_1compare_1func
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_db_find
 * Signature: (JJ[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_crupp_upscaledb_Database_ups_1db_1find
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_db_get_parameters
 * Signature: (J[Lde/crupp/upscaledb/Parameter;)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Database_ups_1db_1get_1parameters
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_db_insert
 * Signature: (JJ[B[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Database_ups_1db_1insert
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_db_erase
 * Signature: (JJ[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Database_ups_1db_1erase
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_db_bulk_operations
 * Signature: (JJ[Lde/crupp/upscaledb/Operation;I)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Database_ups_1db_1bulk_1operations
  (JNIEnv *, jobject, jlong, jlong, jobjectArray, jint);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_db_count
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Database_ups_1db_1count
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     de_crupp_upscaledb_Database
 * Method:    ups_db_close
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Database_ups_1db_1close
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
