/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_upscaledb_Environment */

#ifndef _Included_de_crupp_upscaledb_Environment
#define _Included_de_crupp_upscaledb_Environment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_create
 * Signature: (Ljava/lang/String;II[Lde/crupp/upscaledb/Parameter;)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1create
  (JNIEnv *, jobject, jstring, jint, jint, jobjectArray);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_open
 * Signature: (Ljava/lang/String;I[Lde/crupp/upscaledb/Parameter;)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1open
  (JNIEnv *, jobject, jstring, jint, jobjectArray);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_create_db
 * Signature: (JSI[Lde/crupp/upscaledb/Parameter;)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1create_1db
  (JNIEnv *, jobject, jlong, jshort, jint, jobjectArray);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_open_db
 * Signature: (JSI[Lde/crupp/upscaledb/Parameter;)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1open_1db
  (JNIEnv *, jobject, jlong, jshort, jint, jobjectArray);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_get_parameters
 * Signature: (J[Lde/crupp/upscaledb/Parameter;)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1get_1parameters
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_rename_db
 * Signature: (JSSI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1rename_1db
  (JNIEnv *, jobject, jlong, jshort, jshort, jint);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_erase_db
 * Signature: (JSI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1erase_1db
  (JNIEnv *, jobject, jlong, jshort, jint);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_get_database_names
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1get_1database_1names
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_flush
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1flush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_txn_begin
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Environment_ups_1txn_1begin
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_select_range
 * Signature: (JLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1select_1range
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong);

/*
 * Class:     de_crupp_upscaledb_Environment
 * Method:    ups_env_close
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Environment_ups_1env_1close
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
