/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_crupp_upscaledb_Cursor */

#ifndef _Included_de_crupp_upscaledb_Cursor
#define _Included_de_crupp_upscaledb_Cursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_create
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1create
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_clone
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1clone
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_move_to
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1move_1to
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_get_key
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1get_1key
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_get_record
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1get_1record
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_overwrite
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1overwrite
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_find
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1find
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_insert
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1insert
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_erase
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1erase
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_get_duplicate_count
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1get_1duplicate_1count
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_get_record_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1get_1record_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_crupp_upscaledb_Cursor
 * Method:    ups_cursor_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_crupp_upscaledb_Cursor_ups_1cursor_1close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
