#
# Copyright (C) Christoph Rupp, 2005, 2006 (chris@crupp.de)
# see file LICENSE for license and copyright information
#
# Scons file for unit tests
#
#

files=[
        "simple.c"
    ]

#cflags    = '-g -pg -Wall -DHAM_DEBUG -DHAM_OS_LIN32'
#include   = ['../include']
libraries = ['hamsterdb']
libpaths  = ['../build']

Import('env')

# set up the environment
env.Program('simple', files, LIBS = libraries, LIBPATH = libpaths)
