/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "messages.pb-c.h"
void   ham__wrapper__init
                     (Ham__Wrapper         *message)
{
  static Ham__Wrapper init_value = HAM__WRAPPER__INIT;
  *message = init_value;
}
size_t ham__wrapper__get_packed_size
                     (const Ham__Wrapper *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__wrapper__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__wrapper__pack
                     (const Ham__Wrapper *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__wrapper__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__wrapper__pack_to_buffer
                     (const Ham__Wrapper *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__wrapper__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__Wrapper *
       ham__wrapper__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__Wrapper *)
     protobuf_c_message_unpack (&ham__wrapper__descriptor,
                                allocator, len, data);
}
void   ham__wrapper__free_unpacked
                     (Ham__Wrapper *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__wrapper__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__connect_request__init
                     (Ham__ConnectRequest         *message)
{
  static Ham__ConnectRequest init_value = HAM__CONNECT_REQUEST__INIT;
  *message = init_value;
}
size_t ham__connect_request__get_packed_size
                     (const Ham__ConnectRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__connect_request__pack
                     (const Ham__ConnectRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__connect_request__pack_to_buffer
                     (const Ham__ConnectRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__ConnectRequest *
       ham__connect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__ConnectRequest *)
     protobuf_c_message_unpack (&ham__connect_request__descriptor,
                                allocator, len, data);
}
void   ham__connect_request__free_unpacked
                     (Ham__ConnectRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__connect_reply__init
                     (Ham__ConnectReply         *message)
{
  static Ham__ConnectReply init_value = HAM__CONNECT_REPLY__INIT;
  *message = init_value;
}
size_t ham__connect_reply__get_packed_size
                     (const Ham__ConnectReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__connect_reply__pack
                     (const Ham__ConnectReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__connect_reply__pack_to_buffer
                     (const Ham__ConnectReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__ConnectReply *
       ham__connect_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__ConnectReply *)
     protobuf_c_message_unpack (&ham__connect_reply__descriptor,
                                allocator, len, data);
}
void   ham__connect_reply__free_unpacked
                     (Ham__ConnectReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__rename_request__init
                     (Ham__RenameRequest         *message)
{
  static Ham__RenameRequest init_value = HAM__RENAME_REQUEST__INIT;
  *message = init_value;
}
size_t ham__rename_request__get_packed_size
                     (const Ham__RenameRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__rename_request__pack
                     (const Ham__RenameRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__rename_request__pack_to_buffer
                     (const Ham__RenameRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__RenameRequest *
       ham__rename_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__RenameRequest *)
     protobuf_c_message_unpack (&ham__rename_request__descriptor,
                                allocator, len, data);
}
void   ham__rename_request__free_unpacked
                     (Ham__RenameRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__rename_reply__init
                     (Ham__RenameReply         *message)
{
  static Ham__RenameReply init_value = HAM__RENAME_REPLY__INIT;
  *message = init_value;
}
size_t ham__rename_reply__get_packed_size
                     (const Ham__RenameReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__rename_reply__pack
                     (const Ham__RenameReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__rename_reply__pack_to_buffer
                     (const Ham__RenameReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__RenameReply *
       ham__rename_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__RenameReply *)
     protobuf_c_message_unpack (&ham__rename_reply__descriptor,
                                allocator, len, data);
}
void   ham__rename_reply__free_unpacked
                     (Ham__RenameReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue ham__wrapper__type__enum_values_by_number[4] =
{
  { "CONNECT_REQUEST", "HAM__WRAPPER__TYPE__CONNECT_REQUEST", 10 },
  { "CONNECT_REPLY", "HAM__WRAPPER__TYPE__CONNECT_REPLY", 11 },
  { "RENAME_REQUEST", "HAM__WRAPPER__TYPE__RENAME_REQUEST", 20 },
  { "RENAME_REPLY", "HAM__WRAPPER__TYPE__RENAME_REPLY", 21 },
};
static const ProtobufCIntRange ham__wrapper__type__value_ranges[] = {
{10, 0},{20, 2},{0, 4}
};
const ProtobufCEnumValueIndex ham__wrapper__type__enum_values_by_name[4] =
{
  { "CONNECT_REPLY", 1 },
  { "CONNECT_REQUEST", 0 },
  { "RENAME_REPLY", 3 },
  { "RENAME_REQUEST", 2 },
};
const ProtobufCEnumDescriptor ham__wrapper__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "ham.Wrapper.Type",
  "Type",
  "Ham__Wrapper__Type",
  "ham",
  4,
  ham__wrapper__type__enum_values_by_number,
  4,
  ham__wrapper__type__enum_values_by_name,
  2,
  ham__wrapper__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ham__wrapper__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, type),
    &ham__wrapper__type__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "connect_request",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, connect_request),
    &ham__connect_request__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "connect_reply",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, connect_reply),
    &ham__connect_reply__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "rename_request",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, rename_request),
    &ham__rename_request__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "rename_reply",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, rename_reply),
    &ham__rename_reply__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__wrapper__field_indices_by_name[] = {
  2,   /* field[2] = connect_reply */
  1,   /* field[1] = connect_request */
  4,   /* field[4] = rename_reply */
  3,   /* field[3] = rename_request */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ham__wrapper__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 20, 3 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ham__wrapper__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.Wrapper",
  "Wrapper",
  "Ham__Wrapper",
  "ham",
  sizeof(Ham__Wrapper),
  5,
  ham__wrapper__field_descriptors,
  ham__wrapper__field_indices_by_name,
  3,  ham__wrapper__number_ranges,
  (ProtobufCMessageInit) ham__wrapper__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__connect_request__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectRequest, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectRequest, path),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__connect_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = path */
};
static const ProtobufCIntRange ham__connect_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__connect_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.ConnectRequest",
  "ConnectRequest",
  "Ham__ConnectRequest",
  "ham",
  sizeof(Ham__ConnectRequest),
  2,
  ham__connect_request__field_descriptors,
  ham__connect_request__field_indices_by_name,
  1,  ham__connect_request__number_ranges,
  (ProtobufCMessageInit) ham__connect_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__connect_reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectReply, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectReply, status),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__connect_reply__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ham__connect_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__connect_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.ConnectReply",
  "ConnectReply",
  "Ham__ConnectReply",
  "ham",
  sizeof(Ham__ConnectReply),
  2,
  ham__connect_reply__field_descriptors,
  ham__connect_reply__field_indices_by_name,
  1,  ham__connect_reply__number_ranges,
  (ProtobufCMessageInit) ham__connect_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__rename_request__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__RenameRequest, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "oldname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__RenameRequest, oldname),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "newname",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__RenameRequest, newname),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "flags",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__RenameRequest, flags),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__rename_request__field_indices_by_name[] = {
  3,   /* field[3] = flags */
  0,   /* field[0] = id */
  2,   /* field[2] = newname */
  1,   /* field[1] = oldname */
};
static const ProtobufCIntRange ham__rename_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ham__rename_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.RenameRequest",
  "RenameRequest",
  "Ham__RenameRequest",
  "ham",
  sizeof(Ham__RenameRequest),
  4,
  ham__rename_request__field_descriptors,
  ham__rename_request__field_indices_by_name,
  1,  ham__rename_request__number_ranges,
  (ProtobufCMessageInit) ham__rename_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__rename_reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__RenameReply, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__RenameReply, status),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__rename_reply__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ham__rename_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__rename_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.RenameReply",
  "RenameReply",
  "Ham__RenameReply",
  "ham",
  sizeof(Ham__RenameReply),
  2,
  ham__rename_reply__field_descriptors,
  ham__rename_reply__field_indices_by_name,
  1,  ham__rename_reply__number_ranges,
  (ProtobufCMessageInit) ham__rename_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
