/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "messages.pb-c.h"
void   ham__wrapper__init
                     (Ham__Wrapper         *message)
{
  static Ham__Wrapper init_value = HAM__WRAPPER__INIT;
  *message = init_value;
}
size_t ham__wrapper__get_packed_size
                     (const Ham__Wrapper *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__wrapper__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__wrapper__pack
                     (const Ham__Wrapper *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__wrapper__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__wrapper__pack_to_buffer
                     (const Ham__Wrapper *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__wrapper__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__Wrapper *
       ham__wrapper__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__Wrapper *)
     protobuf_c_message_unpack (&ham__wrapper__descriptor,
                                allocator, len, data);
}
void   ham__wrapper__free_unpacked
                     (Ham__Wrapper *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__wrapper__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__connect_request__init
                     (Ham__ConnectRequest         *message)
{
  static Ham__ConnectRequest init_value = HAM__CONNECT_REQUEST__INIT;
  *message = init_value;
}
size_t ham__connect_request__get_packed_size
                     (const Ham__ConnectRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__connect_request__pack
                     (const Ham__ConnectRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__connect_request__pack_to_buffer
                     (const Ham__ConnectRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__ConnectRequest *
       ham__connect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__ConnectRequest *)
     protobuf_c_message_unpack (&ham__connect_request__descriptor,
                                allocator, len, data);
}
void   ham__connect_request__free_unpacked
                     (Ham__ConnectRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__connect_reply__init
                     (Ham__ConnectReply         *message)
{
  static Ham__ConnectReply init_value = HAM__CONNECT_REPLY__INIT;
  *message = init_value;
}
size_t ham__connect_reply__get_packed_size
                     (const Ham__ConnectReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__connect_reply__pack
                     (const Ham__ConnectReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__connect_reply__pack_to_buffer
                     (const Ham__ConnectReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__ConnectReply *
       ham__connect_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__ConnectReply *)
     protobuf_c_message_unpack (&ham__connect_reply__descriptor,
                                allocator, len, data);
}
void   ham__connect_reply__free_unpacked
                     (Ham__ConnectReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__env_get_parameters_request__init
                     (Ham__EnvGetParametersRequest         *message)
{
  static Ham__EnvGetParametersRequest init_value = HAM__ENV_GET_PARAMETERS_REQUEST__INIT;
  *message = init_value;
}
size_t ham__env_get_parameters_request__get_packed_size
                     (const Ham__EnvGetParametersRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_parameters_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__env_get_parameters_request__pack
                     (const Ham__EnvGetParametersRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_parameters_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__env_get_parameters_request__pack_to_buffer
                     (const Ham__EnvGetParametersRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_parameters_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__EnvGetParametersRequest *
       ham__env_get_parameters_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__EnvGetParametersRequest *)
     protobuf_c_message_unpack (&ham__env_get_parameters_request__descriptor,
                                allocator, len, data);
}
void   ham__env_get_parameters_request__free_unpacked
                     (Ham__EnvGetParametersRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_parameters_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__env_get_parameters_reply__init
                     (Ham__EnvGetParametersReply         *message)
{
  static Ham__EnvGetParametersReply init_value = HAM__ENV_GET_PARAMETERS_REPLY__INIT;
  *message = init_value;
}
size_t ham__env_get_parameters_reply__get_packed_size
                     (const Ham__EnvGetParametersReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_parameters_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__env_get_parameters_reply__pack
                     (const Ham__EnvGetParametersReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_parameters_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__env_get_parameters_reply__pack_to_buffer
                     (const Ham__EnvGetParametersReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_parameters_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__EnvGetParametersReply *
       ham__env_get_parameters_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__EnvGetParametersReply *)
     protobuf_c_message_unpack (&ham__env_get_parameters_reply__descriptor,
                                allocator, len, data);
}
void   ham__env_get_parameters_reply__free_unpacked
                     (Ham__EnvGetParametersReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_parameters_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__env_get_database_names_request__init
                     (Ham__EnvGetDatabaseNamesRequest         *message)
{
  static Ham__EnvGetDatabaseNamesRequest init_value = HAM__ENV_GET_DATABASE_NAMES_REQUEST__INIT;
  *message = init_value;
}
size_t ham__env_get_database_names_request__get_packed_size
                     (const Ham__EnvGetDatabaseNamesRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_database_names_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__env_get_database_names_request__pack
                     (const Ham__EnvGetDatabaseNamesRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_database_names_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__env_get_database_names_request__pack_to_buffer
                     (const Ham__EnvGetDatabaseNamesRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_database_names_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__EnvGetDatabaseNamesRequest *
       ham__env_get_database_names_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__EnvGetDatabaseNamesRequest *)
     protobuf_c_message_unpack (&ham__env_get_database_names_request__descriptor,
                                allocator, len, data);
}
void   ham__env_get_database_names_request__free_unpacked
                     (Ham__EnvGetDatabaseNamesRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_database_names_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__env_get_database_names_reply__init
                     (Ham__EnvGetDatabaseNamesReply         *message)
{
  static Ham__EnvGetDatabaseNamesReply init_value = HAM__ENV_GET_DATABASE_NAMES_REPLY__INIT;
  *message = init_value;
}
size_t ham__env_get_database_names_reply__get_packed_size
                     (const Ham__EnvGetDatabaseNamesReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_database_names_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__env_get_database_names_reply__pack
                     (const Ham__EnvGetDatabaseNamesReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_database_names_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__env_get_database_names_reply__pack_to_buffer
                     (const Ham__EnvGetDatabaseNamesReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_database_names_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__EnvGetDatabaseNamesReply *
       ham__env_get_database_names_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__EnvGetDatabaseNamesReply *)
     protobuf_c_message_unpack (&ham__env_get_database_names_reply__descriptor,
                                allocator, len, data);
}
void   ham__env_get_database_names_reply__free_unpacked
                     (Ham__EnvGetDatabaseNamesReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_get_database_names_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__env_rename_request__init
                     (Ham__EnvRenameRequest         *message)
{
  static Ham__EnvRenameRequest init_value = HAM__ENV_RENAME_REQUEST__INIT;
  *message = init_value;
}
size_t ham__env_rename_request__get_packed_size
                     (const Ham__EnvRenameRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_rename_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__env_rename_request__pack
                     (const Ham__EnvRenameRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_rename_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__env_rename_request__pack_to_buffer
                     (const Ham__EnvRenameRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_rename_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__EnvRenameRequest *
       ham__env_rename_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__EnvRenameRequest *)
     protobuf_c_message_unpack (&ham__env_rename_request__descriptor,
                                allocator, len, data);
}
void   ham__env_rename_request__free_unpacked
                     (Ham__EnvRenameRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_rename_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__env_rename_reply__init
                     (Ham__EnvRenameReply         *message)
{
  static Ham__EnvRenameReply init_value = HAM__ENV_RENAME_REPLY__INIT;
  *message = init_value;
}
size_t ham__env_rename_reply__get_packed_size
                     (const Ham__EnvRenameReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_rename_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__env_rename_reply__pack
                     (const Ham__EnvRenameReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_rename_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__env_rename_reply__pack_to_buffer
                     (const Ham__EnvRenameReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_rename_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__EnvRenameReply *
       ham__env_rename_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__EnvRenameReply *)
     protobuf_c_message_unpack (&ham__env_rename_reply__descriptor,
                                allocator, len, data);
}
void   ham__env_rename_reply__free_unpacked
                     (Ham__EnvRenameReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_rename_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__env_flush_request__init
                     (Ham__EnvFlushRequest         *message)
{
  static Ham__EnvFlushRequest init_value = HAM__ENV_FLUSH_REQUEST__INIT;
  *message = init_value;
}
size_t ham__env_flush_request__get_packed_size
                     (const Ham__EnvFlushRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_flush_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__env_flush_request__pack
                     (const Ham__EnvFlushRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_flush_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__env_flush_request__pack_to_buffer
                     (const Ham__EnvFlushRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_flush_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__EnvFlushRequest *
       ham__env_flush_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__EnvFlushRequest *)
     protobuf_c_message_unpack (&ham__env_flush_request__descriptor,
                                allocator, len, data);
}
void   ham__env_flush_request__free_unpacked
                     (Ham__EnvFlushRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_flush_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__env_flush_reply__init
                     (Ham__EnvFlushReply         *message)
{
  static Ham__EnvFlushReply init_value = HAM__ENV_FLUSH_REPLY__INIT;
  *message = init_value;
}
size_t ham__env_flush_reply__get_packed_size
                     (const Ham__EnvFlushReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_flush_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__env_flush_reply__pack
                     (const Ham__EnvFlushReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_flush_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__env_flush_reply__pack_to_buffer
                     (const Ham__EnvFlushReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_flush_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__EnvFlushReply *
       ham__env_flush_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__EnvFlushReply *)
     protobuf_c_message_unpack (&ham__env_flush_reply__descriptor,
                                allocator, len, data);
}
void   ham__env_flush_reply__free_unpacked
                     (Ham__EnvFlushReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__env_flush_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue ham__wrapper__type__enum_values_by_number[10] =
{
  { "CONNECT_REQUEST", "HAM__WRAPPER__TYPE__CONNECT_REQUEST", 10 },
  { "CONNECT_REPLY", "HAM__WRAPPER__TYPE__CONNECT_REPLY", 11 },
  { "ENV_RENAME_REQUEST", "HAM__WRAPPER__TYPE__ENV_RENAME_REQUEST", 20 },
  { "ENV_RENAME_REPLY", "HAM__WRAPPER__TYPE__ENV_RENAME_REPLY", 21 },
  { "ENV_GET_PARAMETERS_REQUEST", "HAM__WRAPPER__TYPE__ENV_GET_PARAMETERS_REQUEST", 30 },
  { "ENV_GET_PARAMETERS_REPLY", "HAM__WRAPPER__TYPE__ENV_GET_PARAMETERS_REPLY", 31 },
  { "ENV_GET_DATABASE_NAMES_REQUEST", "HAM__WRAPPER__TYPE__ENV_GET_DATABASE_NAMES_REQUEST", 40 },
  { "ENV_GET_DATABASE_NAMES_REPLY", "HAM__WRAPPER__TYPE__ENV_GET_DATABASE_NAMES_REPLY", 41 },
  { "ENV_FLUSH_REQUEST", "HAM__WRAPPER__TYPE__ENV_FLUSH_REQUEST", 50 },
  { "ENV_FLUSH_REPLY", "HAM__WRAPPER__TYPE__ENV_FLUSH_REPLY", 51 },
};
static const ProtobufCIntRange ham__wrapper__type__value_ranges[] = {
{10, 0},{20, 2},{30, 4},{40, 6},{50, 8},{0, 10}
};
const ProtobufCEnumValueIndex ham__wrapper__type__enum_values_by_name[10] =
{
  { "CONNECT_REPLY", 1 },
  { "CONNECT_REQUEST", 0 },
  { "ENV_FLUSH_REPLY", 9 },
  { "ENV_FLUSH_REQUEST", 8 },
  { "ENV_GET_DATABASE_NAMES_REPLY", 7 },
  { "ENV_GET_DATABASE_NAMES_REQUEST", 6 },
  { "ENV_GET_PARAMETERS_REPLY", 5 },
  { "ENV_GET_PARAMETERS_REQUEST", 4 },
  { "ENV_RENAME_REPLY", 3 },
  { "ENV_RENAME_REQUEST", 2 },
};
const ProtobufCEnumDescriptor ham__wrapper__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "ham.Wrapper.Type",
  "Type",
  "Ham__Wrapper__Type",
  "ham",
  10,
  ham__wrapper__type__enum_values_by_number,
  10,
  ham__wrapper__type__enum_values_by_name,
  5,
  ham__wrapper__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ham__wrapper__field_descriptors[11] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, type),
    &ham__wrapper__type__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "connect_request",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, connect_request),
    &ham__connect_request__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "connect_reply",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, connect_reply),
    &ham__connect_reply__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "env_rename_request",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, env_rename_request),
    &ham__env_rename_request__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "env_rename_reply",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, env_rename_reply),
    &ham__env_rename_reply__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "env_get_parameters_request",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, env_get_parameters_request),
    &ham__env_get_parameters_request__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "env_get_parameters_reply",
    32,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, env_get_parameters_reply),
    &ham__env_get_parameters_reply__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "env_get_database_names_request",
    41,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, env_get_database_names_request),
    &ham__env_get_database_names_request__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "env_get_database_names_reply",
    42,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, env_get_database_names_reply),
    &ham__env_get_database_names_reply__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "env_flush_request",
    51,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, env_flush_request),
    &ham__env_flush_request__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "env_flush_reply",
    52,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Wrapper, env_flush_reply),
    &ham__env_flush_reply__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__wrapper__field_indices_by_name[] = {
  2,   /* field[2] = connect_reply */
  1,   /* field[1] = connect_request */
  10,   /* field[10] = env_flush_reply */
  9,   /* field[9] = env_flush_request */
  8,   /* field[8] = env_get_database_names_reply */
  7,   /* field[7] = env_get_database_names_request */
  6,   /* field[6] = env_get_parameters_reply */
  5,   /* field[5] = env_get_parameters_request */
  4,   /* field[4] = env_rename_reply */
  3,   /* field[3] = env_rename_request */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ham__wrapper__number_ranges[6 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 20, 3 },
  { 31, 5 },
  { 41, 7 },
  { 51, 9 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor ham__wrapper__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.Wrapper",
  "Wrapper",
  "Ham__Wrapper",
  "ham",
  sizeof(Ham__Wrapper),
  11,
  ham__wrapper__field_descriptors,
  ham__wrapper__field_indices_by_name,
  6,  ham__wrapper__number_ranges,
  (ProtobufCMessageInit) ham__wrapper__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__connect_request__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectRequest, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectRequest, path),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__connect_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = path */
};
static const ProtobufCIntRange ham__connect_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__connect_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.ConnectRequest",
  "ConnectRequest",
  "Ham__ConnectRequest",
  "ham",
  sizeof(Ham__ConnectRequest),
  2,
  ham__connect_request__field_descriptors,
  ham__connect_request__field_indices_by_name,
  1,  ham__connect_request__number_ranges,
  (ProtobufCMessageInit) ham__connect_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__connect_reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectReply, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectReply, status),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__connect_reply__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ham__connect_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__connect_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.ConnectReply",
  "ConnectReply",
  "Ham__ConnectReply",
  "ham",
  sizeof(Ham__ConnectReply),
  2,
  ham__connect_reply__field_descriptors,
  ham__connect_reply__field_indices_by_name,
  1,  ham__connect_reply__number_ranges,
  (ProtobufCMessageInit) ham__connect_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__env_get_parameters_request__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersRequest, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "names",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersRequest, n_names),
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersRequest, names),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__env_get_parameters_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = names */
};
static const ProtobufCIntRange ham__env_get_parameters_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__env_get_parameters_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.EnvGetParametersRequest",
  "EnvGetParametersRequest",
  "Ham__EnvGetParametersRequest",
  "ham",
  sizeof(Ham__EnvGetParametersRequest),
  2,
  ham__env_get_parameters_request__field_descriptors,
  ham__env_get_parameters_request__field_indices_by_name,
  1,  ham__env_get_parameters_request__number_ranges,
  (ProtobufCMessageInit) ham__env_get_parameters_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__env_get_parameters_reply__field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, status),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "cachesize",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, has_cachesize),
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, cachesize),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "pagesize",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, has_pagesize),
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, pagesize),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "max_env_databases",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, has_max_env_databases),
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, max_env_databases),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "flags",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, has_flags),
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, flags),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "filemode",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, has_filemode),
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, filemode),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "filename",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvGetParametersReply, filename),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__env_get_parameters_reply__field_indices_by_name[] = {
  2,   /* field[2] = cachesize */
  6,   /* field[6] = filemode */
  7,   /* field[7] = filename */
  5,   /* field[5] = flags */
  0,   /* field[0] = id */
  4,   /* field[4] = max_env_databases */
  3,   /* field[3] = pagesize */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ham__env_get_parameters_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ham__env_get_parameters_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.EnvGetParametersReply",
  "EnvGetParametersReply",
  "Ham__EnvGetParametersReply",
  "ham",
  sizeof(Ham__EnvGetParametersReply),
  8,
  ham__env_get_parameters_reply__field_descriptors,
  ham__env_get_parameters_reply__field_indices_by_name,
  1,  ham__env_get_parameters_reply__number_ranges,
  (ProtobufCMessageInit) ham__env_get_parameters_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__env_get_database_names_request__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvGetDatabaseNamesRequest, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__env_get_database_names_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange ham__env_get_database_names_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ham__env_get_database_names_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.EnvGetDatabaseNamesRequest",
  "EnvGetDatabaseNamesRequest",
  "Ham__EnvGetDatabaseNamesRequest",
  "ham",
  sizeof(Ham__EnvGetDatabaseNamesRequest),
  1,
  ham__env_get_database_names_request__field_descriptors,
  ham__env_get_database_names_request__field_indices_by_name,
  1,  ham__env_get_database_names_request__number_ranges,
  (ProtobufCMessageInit) ham__env_get_database_names_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__env_get_database_names_reply__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvGetDatabaseNamesReply, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvGetDatabaseNamesReply, status),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "names",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Ham__EnvGetDatabaseNamesReply, n_names),
    PROTOBUF_C_OFFSETOF(Ham__EnvGetDatabaseNamesReply, names),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__env_get_database_names_reply__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = names */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ham__env_get_database_names_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ham__env_get_database_names_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.EnvGetDatabaseNamesReply",
  "EnvGetDatabaseNamesReply",
  "Ham__EnvGetDatabaseNamesReply",
  "ham",
  sizeof(Ham__EnvGetDatabaseNamesReply),
  3,
  ham__env_get_database_names_reply__field_descriptors,
  ham__env_get_database_names_reply__field_indices_by_name,
  1,  ham__env_get_database_names_reply__number_ranges,
  (ProtobufCMessageInit) ham__env_get_database_names_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__env_rename_request__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvRenameRequest, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "oldname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvRenameRequest, oldname),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "newname",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvRenameRequest, newname),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "flags",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvRenameRequest, flags),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__env_rename_request__field_indices_by_name[] = {
  3,   /* field[3] = flags */
  0,   /* field[0] = id */
  2,   /* field[2] = newname */
  1,   /* field[1] = oldname */
};
static const ProtobufCIntRange ham__env_rename_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ham__env_rename_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.EnvRenameRequest",
  "EnvRenameRequest",
  "Ham__EnvRenameRequest",
  "ham",
  sizeof(Ham__EnvRenameRequest),
  4,
  ham__env_rename_request__field_descriptors,
  ham__env_rename_request__field_indices_by_name,
  1,  ham__env_rename_request__number_ranges,
  (ProtobufCMessageInit) ham__env_rename_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__env_rename_reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvRenameReply, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvRenameReply, status),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__env_rename_reply__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ham__env_rename_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__env_rename_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.EnvRenameReply",
  "EnvRenameReply",
  "Ham__EnvRenameReply",
  "ham",
  sizeof(Ham__EnvRenameReply),
  2,
  ham__env_rename_reply__field_descriptors,
  ham__env_rename_reply__field_indices_by_name,
  1,  ham__env_rename_reply__number_ranges,
  (ProtobufCMessageInit) ham__env_rename_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__env_flush_request__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvFlushRequest, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvFlushRequest, flags),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__env_flush_request__field_indices_by_name[] = {
  1,   /* field[1] = flags */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange ham__env_flush_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__env_flush_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.EnvFlushRequest",
  "EnvFlushRequest",
  "Ham__EnvFlushRequest",
  "ham",
  sizeof(Ham__EnvFlushRequest),
  2,
  ham__env_flush_request__field_descriptors,
  ham__env_flush_request__field_indices_by_name,
  1,  ham__env_flush_request__number_ranges,
  (ProtobufCMessageInit) ham__env_flush_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ham__env_flush_reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvFlushReply, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__EnvFlushReply, status),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__env_flush_reply__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ham__env_flush_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__env_flush_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.EnvFlushReply",
  "EnvFlushReply",
  "Ham__EnvFlushReply",
  "ham",
  sizeof(Ham__EnvFlushReply),
  2,
  ham__env_flush_reply__field_descriptors,
  ham__env_flush_reply__field_indices_by_name,
  1,  ham__env_flush_reply__number_ranges,
  (ProtobufCMessageInit) ham__env_flush_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
