/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "messages.pb-c.h"
void   ham__connect__init
                     (Ham__Connect         *message)
{
  static Ham__Connect init_value = HAM__CONNECT__INIT;
  *message = init_value;
}
size_t ham__connect__get_packed_size
                     (const Ham__Connect *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__connect__pack
                     (const Ham__Connect *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__connect__pack_to_buffer
                     (const Ham__Connect *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__Connect *
       ham__connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__Connect *)
     protobuf_c_message_unpack (&ham__connect__descriptor,
                                allocator, len, data);
}
void   ham__connect__free_unpacked
                     (Ham__Connect *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__connect_reply__init
                     (Ham__ConnectReply         *message)
{
  static Ham__ConnectReply init_value = HAM__CONNECT_REPLY__INIT;
  *message = init_value;
}
size_t ham__connect_reply__get_packed_size
                     (const Ham__ConnectReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__connect_reply__pack
                     (const Ham__ConnectReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__connect_reply__pack_to_buffer
                     (const Ham__ConnectReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__ConnectReply *
       ham__connect_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__ConnectReply *)
     protobuf_c_message_unpack (&ham__connect_reply__descriptor,
                                allocator, len, data);
}
void   ham__connect_reply__free_unpacked
                     (Ham__ConnectReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__connect_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__rename__init
                     (Ham__Rename         *message)
{
  static Ham__Rename init_value = HAM__RENAME__INIT;
  *message = init_value;
}
size_t ham__rename__get_packed_size
                     (const Ham__Rename *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__rename__pack
                     (const Ham__Rename *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__rename__pack_to_buffer
                     (const Ham__Rename *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__Rename *
       ham__rename__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__Rename *)
     protobuf_c_message_unpack (&ham__rename__descriptor,
                                allocator, len, data);
}
void   ham__rename__free_unpacked
                     (Ham__Rename *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ham__rename_reply__init
                     (Ham__RenameReply         *message)
{
  static Ham__RenameReply init_value = HAM__RENAME_REPLY__INIT;
  *message = init_value;
}
size_t ham__rename_reply__get_packed_size
                     (const Ham__RenameReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ham__rename_reply__pack
                     (const Ham__RenameReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ham__rename_reply__pack_to_buffer
                     (const Ham__RenameReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ham__RenameReply *
       ham__rename_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ham__RenameReply *)
     protobuf_c_message_unpack (&ham__rename_reply__descriptor,
                                allocator, len, data);
}
void   ham__rename_reply__free_unpacked
                     (Ham__RenameReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ham__rename_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ham__connect__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Connect, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Connect, path),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__connect__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = path */
};
static const ProtobufCIntRange ham__connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__connect__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.Connect",
  "Connect",
  "Ham__Connect",
  "ham",
  sizeof(Ham__Connect),
  2,
  ham__connect__field_descriptors,
  ham__connect__field_indices_by_name,
  1,  ham__connect__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ham__connect_reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectReply, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__ConnectReply, status),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__connect_reply__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ham__connect_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__connect_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.ConnectReply",
  "ConnectReply",
  "Ham__ConnectReply",
  "ham",
  sizeof(Ham__ConnectReply),
  2,
  ham__connect_reply__field_descriptors,
  ham__connect_reply__field_indices_by_name,
  1,  ham__connect_reply__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ham__rename__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Rename, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "oldname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Rename, oldname),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "newname",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Rename, newname),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "flags",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__Rename, flags),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__rename__field_indices_by_name[] = {
  3,   /* field[3] = flags */
  0,   /* field[0] = id */
  2,   /* field[2] = newname */
  1,   /* field[1] = oldname */
};
static const ProtobufCIntRange ham__rename__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ham__rename__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.Rename",
  "Rename",
  "Ham__Rename",
  "ham",
  sizeof(Ham__Rename),
  4,
  ham__rename__field_descriptors,
  ham__rename__field_indices_by_name,
  1,  ham__rename__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ham__rename_reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__RenameReply, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ham__RenameReply, status),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned ham__rename_reply__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ham__rename_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ham__rename_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ham.RenameReply",
  "RenameReply",
  "Ham__RenameReply",
  "ham",
  sizeof(Ham__RenameReply),
  2,
  ham__rename_reply__field_descriptors,
  ham__rename_reply__field_indices_by_name,
  1,  ham__rename_reply__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
