#
# Copyright (C) Christoph Rupp, 2005, 2006 (chris@crupp.de)
# see file LICENSE for license and copyright information
#
# Scons file for hamster-db
#
#

Import('vprint env')

# source files (without extension)
files=[ "db", 
        "error", 
        "mem", 
        "os",
        "page",
        "freelist",
        "txn",
        "util",
        "blob",
        "cache",
        "keys",
        "extkeys",
        "hamsterdb",
        "btree",
        "btree_insert",
        "btree_erase",
        "btree_find",
        "btree_check",
        "btree_enum"
    ]

# workaround for the SCons error message "Source file blah is static and is not 
# compatible with shared target". 
env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME'] = 1

olist=[]
for f in files:
    obj=env.Object('../'+env['buildpath']+'/'+f, f+".c")
    olist.append(obj)

# static or dynamic library?
if env['static']:
    s=env.StaticLibrary('../build/hamsterdb', olist)
    env.Install('/usr/local/lib', s)
else:
    s=env.SharedLibrary('../build/hamsterdb', olist)
    env.Install('/usr/local/lib', s)

env.Alias('install', '/usr/local/lib')
